import type {
  MeasurementCaptureMetadata,
  MeasurementDiagnosticsValues,
} from '#shared/types/protocol'
import type { MeasurementAnalysis, SweepDetection } from './response'

export function createMeasurementDiagnostics(
  child: MeasurementAnalysis,
  channel: 'left' | 'right',
  detection: SweepDetection,
  captureMetadata: MeasurementCaptureMetadata | null,
): MeasurementDiagnosticsValues {
  return {
    channel,
    analysisStatus: child.status,
    failureReason: child.diagnostics.failureReason,
    signalRms: child.diagnostics.signalRms,
    signalPeak: child.diagnostics.signalPeak,
    snrEstimateDb: Number.isFinite(child.diagnostics.snrEstimateDb ?? Number.NaN) ? child.diagnostics.snrEstimateDb : null,
    detectionOffsetMs: Number.isFinite(child.diagnostics.detectionOffsetMs ?? Number.NaN) ? child.diagnostics.detectionOffsetMs : null,
    envelopeOnlyOffsetMs: Number.isFinite(child.diagnostics.envelopeOnlyOffsetMs ?? Number.NaN) ? child.diagnostics.envelopeOnlyOffsetMs : null,
    startMarkerSample: detection.leadingMarkerSample,
    endMarkerSample: detection.trailingMarkerSample,
    expectedMarkerSeparationSamples: detection.expectedMarkerSeparationSamples,
    observedMarkerSeparationSamples: detection.observedMarkerSeparationSamples,
    syncMarkerConfidence: child.diagnostics.rawLeadingMarkerConfidence,
    endingMarkerConfidence: child.diagnostics.endingMarkerConfidence,
    rawLeadingMarkerConfidence: child.diagnostics.rawLeadingMarkerConfidence,
    rawTrailingMarkerConfidence: child.diagnostics.rawTrailingMarkerConfidence,
    bestLeadingMarkerSample: child.diagnostics.bestLeadingMarkerSample,
    bestTrailingMarkerSample: child.diagnostics.bestTrailingMarkerSample,
    leadingMarkerCandidates: child.diagnostics.leadingMarkerCandidates,
    trailingMarkerCandidates: child.diagnostics.trailingMarkerCandidates,
    markerPairCandidates: child.diagnostics.markerPairCandidates,
    leadingBestCorrelation: child.diagnostics.leadingBestCorrelation,
    leadingSecondCorrelation: child.diagnostics.leadingSecondCorrelation,
    leadingCorrelationMargin: child.diagnostics.leadingCorrelationMargin,
    trailingBestCorrelation: child.diagnostics.trailingBestCorrelation,
    trailingSecondCorrelation: child.diagnostics.trailingSecondCorrelation,
    trailingCorrelationMargin: child.diagnostics.trailingCorrelationMargin,
    markerPairScore: child.diagnostics.markerPairScore,
    secondMarkerPairScore: child.diagnostics.secondMarkerPairScore,
    markerPairScoreMargin: child.diagnostics.markerPairScoreMargin,
    markerPairScoreRatio: child.diagnostics.markerPairScoreRatio,
    markerSeparationError: child.diagnostics.markerSeparationError,
    markerTimingAgreement: child.diagnostics.markerTimingAgreement,
    markerSeparationPpm: child.diagnostics.markerSeparationPpm,
    syncMarkerFailureReason: child.diagnostics.syncMarkerFailureReason,
    clockDriftPpm: Number.isFinite(child.diagnostics.clockDriftPpm ?? Number.NaN) ? child.diagnostics.clockDriftPpm : null,
    clipped: child.diagnostics.clipped,
    clippedSamples: child.diagnostics.clippedSamples,
    directArrivalMs: child.room?.directArrivalMs ?? null,
    directPeak: child.diagnostics.directPeak ?? child.impulse?.directArrival.directPeak ?? null,
    deconvolvedNoiseFloorRms: child.diagnostics.deconvolvedNoiseFloorRms ?? child.impulse?.directArrival.noiseFloorRms ?? null,
    directPeakToNoiseDb: child.diagnostics.directPeakToNoiseDb ?? child.impulse?.directArrival.peakToNoiseDb ?? null,
    directArrivalAcceptanceThreshold: child.diagnostics.directArrivalAcceptanceThreshold ?? child.impulse?.directArrival.acceptanceThreshold ?? null,
    directArrivalCandidateSample: child.diagnostics.directArrivalCandidateSample ?? child.impulse?.directArrival.candidateArrivalIndex ?? null,
    directArrivalAcceptedSample: child.diagnostics.directArrivalAcceptedSample ?? child.impulse?.directArrival.acceptedArrivalIndex ?? null,
    directArrivalRejectionReason: child.diagnostics.directArrivalRejectionReason ?? child.impulse?.directArrival.rejectionReason ?? null,
    directSupportWindowRms: child.diagnostics.directSupportWindowRms ?? child.impulse?.directArrival.supportWindowRms ?? null,
    directSupportWindowThreshold: child.diagnostics.directSupportWindowThreshold ?? child.impulse?.directArrival.supportWindowThreshold ?? null,
    directSupportSampleCount: child.diagnostics.directSupportSampleCount ?? child.impulse?.directArrival.supportSampleCount ?? null,
    bestLaterReflectionSample: child.diagnostics.bestLaterReflectionSample ?? child.impulse?.directArrival.laterReflectionIndex ?? null,
    bestLaterReflectionPeak: child.diagnostics.bestLaterReflectionPeak ?? child.impulse?.directArrival.laterReflectionPeak ?? null,
    candidateAbsoluteTimeMs: child.diagnostics.candidateAbsoluteTimeMs ?? child.impulse?.directArrival.candidateAbsoluteTimeMs ?? null,
    earlySearchWindowStartSample: child.diagnostics.earlySearchWindowStartSample ?? child.impulse?.directArrival.earlySearchWindowStartSample ?? null,
    earlySearchWindowEndSample: child.diagnostics.earlySearchWindowEndSample ?? child.impulse?.directArrival.earlySearchWindowEndSample ?? null,
    topEarlyImpulsePeaks: child.diagnostics.topEarlyImpulsePeaks ?? child.impulse?.directArrival.topEarlyImpulsePeaks,
    strongestLaterReflectionDelayMs: child.diagnostics.strongestLaterReflectionDelayMs ?? child.impulse?.directArrival.strongestLaterReflectionDelayMs ?? null,
    localSupportWindowStartSample: child.diagnostics.localSupportWindowStartSample ?? child.impulse?.directArrival.localSupportWindowStartSample ?? null,
    localSupportWindowEndSample: child.diagnostics.localSupportWindowEndSample ?? child.impulse?.directArrival.localSupportWindowEndSample ?? null,
    localSupportWindowMax: child.diagnostics.localSupportWindowMax ?? child.impulse?.directArrival.localSupportWindowMax ?? null,
    localSupportSampleCount: child.diagnostics.localSupportSampleCount ?? child.impulse?.directArrival.localSupportSampleCount ?? null,
    directToLateDb: child.room?.directToLateDb ?? null,
    c50Db: child.room?.c50Db ?? null,
    c80Db: child.room?.c80Db ?? null,
    edtMs: child.room?.edtMs ?? null,
    t20Ms: child.room?.t20Ms ?? null,
    t30Ms: child.room?.t30Ms ?? null,
    earlyReflections: child.room?.earlyReflections.length ?? 0,
    decayConfidence: child.room?.decayConfidence ?? 'low',
    ...(captureMetadata ? { captureMetadata } : {}),
  }
}

export function suppressRepairChannelDiagnostics(
  diagnostics: MeasurementDiagnosticsValues,
  repairChannel: 'both' | 'left' | 'right',
  channel: 'left' | 'right',
): MeasurementDiagnosticsValues {
  if (repairChannel === 'both' || repairChannel === channel) return diagnostics
  return {
    ...diagnostics,
    analysisStatus: 'not_measured',
    failureReason: null,
    syncMarkerFailureReason: null,
    snrEstimateDb: null,
    directArrivalMs: null,
    directArrivalRejectionReason: null,
  }
}
